### ISSUE TITLE
Use new Minecraft title and Java Edition subtitle

### ISSUE THREAD

**Issue by Poopooracoocoo** [ClassicFaithful/32x-Jappa#3]
Classic Faithful:
![image](https://user-images.githubusercontent.com/51363864/152818331-fe14b80f-8608-4d37-80c7-fd1433636ed1.png)

Minecraft Launcher:
![image](https://user-images.githubusercontent.com/51363864/152818389-09db45d1-50e2-4d72-84b2-3b799ede0dcd.png)

**Comment by 3vorp** [comment]
this inconsistency is in default, we can't really change that

**Comment by Poopooracoocoo** [comment]
understood.

**Comment by Poopooracoocoo** [comment]
So I created an issue on MOJIRA and they closed it. They called it a feature request with no explanation of why they interpreted it as one. Logo consistency isn't much of a "feature" :/
