### ISSUE TITLE
What about optimizing images?

### ISSUE THREAD

**Issue by K0-RR** [ClassicFaithful/32x-Jappa#4]
Hello, my plan was to fork ClassicFaithful assets repositories and after lossless compression submit PRs but I figured I would ask first what do You think about it.

There is no downside to this and the resource pack size will just get smaller. The easiest way to achieve this would be to just use GitHub [Imgbot](https://imgbot.net/) as it doesn't require any actions from You other than adding it to the repo with one or two clicks. Imgbot however doesn't do the job as good (still better than nothing) as the tools I use: [Leanify](https://github.com/JayXon/Leanify) and [Oxipng](https://github.com/shssoichiro/oxipng).

Can I proceed or do You prefer to do it by yourself / not interested at all?

**Comment by 3vorp** [comment]
That would be great. 

Just a thing to keep in mind: Colormode converted to grayscale extures messes up pre-1.12 from what I know so try not to do that if possible, bedrock might also have problems with that given how broken it is.

**Comment by 3vorp** [comment]
Update on this, I have tried to run Oxipng on the pack and there is a major issue from what I've found. It doesn't seem to handle translucency very well, for example the glass blocks seem to change all alpha pixels to just the 0 alpha mask color. I messed around with the settings a bit but couldn't find a good way to do it.

If you know a better way than I do, please feel free to submit a PR with the compressed files whenever you can. Thanks for waiting like two months lol.

**Comment by 3vorp** [comment]
Another two months later, another update.

Unfortunately, Minecraft does not take too well to lossless compression on Bedrock Edition or versions below 1.12, both of which we support. This means that we'd either have to specifically compress images for particular versions, which would require a lot of upkeep, or not at all.
