### ISSUE TITLE
1.19.4 Creative mode inventory

### ISSUE THREAD

**Issue by Volkor3-16** [ClassicFaithful/32x-Jappa#8]
I'd fix this myself but It's only an issue to people in creative mode and I have no idea /how/ to fix it.

![javaw_lAnR3YVScf](https://user-images.githubusercontent.com/4054374/232288867-a108444c-561d-40b0-8aa4-cea24c303bf0.png)

**Comment by Volkor3-16** [comment]
I should download the latest version from the website, and not from curse.

**Comment by 3vorp** [comment]
1.19.3+ and 1.19.2- are different versions for a reason — make sure you download the correct version
